[2024-05-12T04:53:35.990+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T04:53:36.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data_Extraction_Transformation_Loading_5.dvc_init scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T04:53:36.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data_Extraction_Transformation_Loading_5.dvc_init scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T04:53:36.068+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-12T04:53:36.127+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_init> on 2024-05-11 00:00:00+00:00
[2024-05-12T04:53:36.138+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Data_Extraction_Transformation_Loading_5', 'dvc_init', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/i202478_dag.py', '--cfg-path', '/tmp/tmpvx3_hz7s']
[2024-05-12T04:53:36.141+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask dvc_init
[2024-05-12T04:53:36.147+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T04:53:36.148+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-05-12T04:53:36.298+0000] {task_command.py:426} INFO - Running <TaskInstance: Data_Extraction_Transformation_Loading_5.dvc_init scheduled__2024-05-11T00:00:00+00:00 [running]> on host 2b962c56fbea
[2024-05-12T04:53:36.482+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Data_Extraction_Transformation_Loading_5' AIRFLOW_CTX_TASK_ID='dvc_init' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-12T04:53:36.484+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T04:53:36.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T04:53:36.580+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dvc init --force']
[2024-05-12T04:53:36.589+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T04:53:39.877+0000] {subprocess.py:93} INFO - ERROR: failed to initiate DVC - /tmp/airflowtmp6rlhn8vz is not tracked by any supported SCM tool (e.g. Git). Use `--no-scm` if you don't want to use any SCM or `--subdir` if initializing inside a subdirectory of a parent SCM repository.
[2024-05-12T04:53:40.179+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-12T04:53:40.181+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T04:53:40.210+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-12T04:53:40.222+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Data_Extraction_Transformation_Loading_5, task_id=dvc_init, run_id=scheduled__2024-05-11T00:00:00+00:00, execution_date=20240511T000000, start_date=20240512T045336, end_date=20240512T045340
[2024-05-12T04:53:40.320+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task dvc_init (Bash command failed. The command returned a non-zero exit code 1.; 71)
[2024-05-12T04:53:40.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T04:53:40.416+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T04:53:40.421+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
